### ISSUE TITLE
Get a pdf output style

### ISSUE THREAD

**Issue by adriens** [sudodoki/reveal-cleaver-theme#4]
Hi sudodoki,

thanks for your very (verry) nice looking theme... the presentation was very successfly and people were impressed by the input... all for plain text ;-p
But now i'd like to share it on slideshare... by uploading a pdf version of the slideshow (https://github.com/jdan/cleaver/issues/116)

... but when i export it, i only manage to get A4 version of the slideshow which does not look good.
Any idea on how to do that export ?

Thank you in advance for your answer and your great theme... loving it.

**Comment by sudodoki** [comment]
@adriens did you try using Landscape option in Print menu?
<img width="1005" alt="screenshot 2015-08-26 20 02 12" src="https://cloud.githubusercontent.com/assets/1506905/9500293/348da600-4c2d-11e5-8bbd-30f1c750efed.png">

**Comment by sudodoki** [comment]
@adriens any luck with this?

**Comment by sudodoki** [comment]
Please, let me know if you need any further help with this.
