### ISSUE TITLE
Need to create an empty settings.json

### ISSUE THREAD

**Issue by lrq3000** [sudodoki/reveal-cleaver-theme#6]
Thank you very much for your great theme, it's been so useful to me (the only dark theme for Cleaver that looks professional currently).

I needed to do a few tweaks to customize the template for my case, so I downloaded the package and set the `theme` parameter in my Markdown to point to my local template folder.

However, Cleaver choke on it, with this error:

```
!! ENOENT: no such file or directory, open 'C:\Users\path\to\reveal-cleaver-
theme-master\settings.json'
```

The solution was to simply create an empty `settings.json` file. Weirdly, Cleaver has no problem with a missing `settings.json` if we point to a git repository.

**Comment by sudodoki** [comment]
can you possibly open this issue on https://github.com/jdan/cleaver and cross-reference this one? Might be a more global issue - otherwise, let me know if you find out what I can tweak in this theme to make it work

**Comment by lrq3000** [comment]
Ok done :)

**Comment by sudodoki** [comment]
Fixed this. @lrq3000 turned out I was using older version of cleaver that didn't require this. Now should be fixed.

**Comment by sudodoki** [comment]
Thanks for reporting, sorry for long response.
