### ISSUE TITLE
Should be able to apply a Reveal theme as well

### ISSUE THREAD

**Issue by elstamey** [sudodoki/reveal-cleaver-theme#7]
Thank you for this!  I have been trying to understand how it works.

I'd like to use a Reveal theme I already have on top of cleaver.  How can I do this?

**Comment by sudodoki** [comment]
@elstamey take a look at https://github.com/sudodoki/reveal-cleaver-theme-bright and https://github.com/sudodoki/reveal-cleaver-theme. Basically, you need to change markup for single slide to feature reveal specific className, as well as one for whole container, include proper js and css. My themes are not fully utilizing functionality provided by reveal (presenter view, etc), which is place of possible improvement. Hope this helps you out and hope you'll get what you need. Try taking look at other [themes](https://github.com/jdan/cleaver/wiki/Theme-Index) which might be useful.
